global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['java-bff-service:8084', 'java-service-managment:8081']
        labels:
          group: 'spring-services'

  - job_name: 'java-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'java-service-filtering:8082', 'java-service-deduplication:8083', 'java-service-enrichment:8085' ]
