spring:
  datasource:
    username: test
    password: test
    url: jdbc:h2:mem:test;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
  liquibase:
    liquibase-schema: public
    default-schema: public
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: public
        format_sql: true

server:
  port: 8080