version: '3.8'

services:

  postgres-app-bff:
    image: postgres:15
    container_name: postgres-app-bff
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_a:/var/lib/postgresql/data
    networks:
      - app-network


  postgres-app-management:
    image: postgres:15
    container_name: postgres-app-management
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_b:/var/lib/postgresql/data
    networks:
      - app-network


  redis-bff:
    image: redis:latest
    container_name: redis-bff
    ports:
      - "6379:6379"
    networks:
      - app-network


  app-management:
    image: app-b-image:latest
    container_name: app-management
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-app-management:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    depends_on:
      - postgres-app-management
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data_a:
    driver: local
  postgres_data_b:
    driver: local